version: '2'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    links:
      - mkdocs
      - reveal
      - elasticsearch
    ports:
      - "80:80"
      - "443:443"

  mkdocs:
    container_name: mkdocs
    build:
      context: ./mkdocs
#      args:
#        project: sample
    environment:
#      Direct Write Endpoint IP or pass through the run-time env variable
#      - ES_ENDPOINT=192.168.100.12
      - ES_ENDPOINT=${HOST_IP}
    command: serve -a 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - elasticsearch
    volumes:
#      - ./mkdocs/$project:/docs/$project
      - ./mkdocs/sample:/docs/sample

  reveal:
    container_name: reveal
    build:
      context: ./mkdocs
#      args:
#        project: sample
#    command: reveal start ${project} docs/${project}.md
    command: reveal start sample docs/sample.md
    ports:
      - "8001:8001"
    volumes:
#      - ./mkdocs/$project:/docs/$project
      - ./mkdocs/sample:/docs/sample

  cron:
    container_name: cron
    build:
      context: ./mkdocs
#      args:
#        project: sample
    command: cron
    links:
      - elasticsearch
    volumes:
#      - ./mkdocs/$project:/docs/$project
      - ./mkdocs/sample:/docs/sample

  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"



